package crypto

import (
	"crypto/rand"
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestEncryptDecrypt(t *testing.T) {
	key := make([]byte, 32)
	_, err := rand.Read(key)
	require.NoError(t, err)

	plaintext := "my-secure-password-123!"

	ciphertext, nonce, err := Encrypt(key, plaintext)
	require.NoError(t, err)
	assert.NotEmpty(t, ciphertext)
	assert.Len(t, nonce, 12)

	decrypted, err := Decrypt(key, ciphertext, nonce)
	require.NoError(t, err)
	assert.Equal(t, plaintext, decrypted)
}

func TestInvalidKeySize(t *testing.T) {
	invalidKey := make([]byte, 16)
	_, _, err := Encrypt(invalidKey, "plaintext")
	assert.Error(t, err)

	_, err = Decrypt(invalidKey, []byte("cipher"), make([]byte, 12))
	assert.Error(t, err)
}

func TestInvalidNonceSize(t *testing.T) {
	key := make([]byte, 32)
	_, err := rand.Read(key)
	require.NoError(t, err)

	_, err = Decrypt(key, []byte("cipher"), make([]byte, 8))
	assert.Error(t, err)
}

func TestPythonCompatibility(t *testing.T) {
	// A known key, nonce, plaintext, and the ciphertext generated by Python
	keyHex := "2b7e151628aed2a6abf7158809cf4f3c2b7e151628aed2a6abf7158809cf4f3c"
	nonceHex := "f20dd459b8005b4a625a6769"
	ciphertextHex := "c10099c0df2d3421ea26c3455519e80411f5f53d29cc935c509fc2" // "hello world" with tag
	expectedPlaintext := "hello world"

	key, err := hex.DecodeString(keyHex)
	require.NoError(t, err)
	nonce, err := hex.DecodeString(nonceHex)
	require.NoError(t, err)
	ciphertext, err := hex.DecodeString(ciphertextHex)
	require.NoError(t, err)

	decrypted, err := Decrypt(key, ciphertext, nonce)
	require.NoError(t, err)
	assert.Equal(t, expectedPlaintext, decrypted)
}
