ARG GO_VERSION=1.26.3-alpine3.23
FROM golang:${GO_VERSION}

# Install build dependencies for CGO and air
RUN apk add --no-cache gcc musl-dev git

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
